name: company-tree

services:

  app:
    build: docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www
    entrypoint: ["php", "get_tree.php"]
